# Generated by Django 5.2.3 on 2025-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_por_dia', models.IntegerField(default=8, help_text='Horas de trabajo por día (considerando todos los trabajadores)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_estimadas', models.IntegerField(help_text='Horas totales estimadas para completar la obra')),
                ('orden', models.IntegerField(default=0, help_text='Orden de ejecución de las obras')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['orden', 'creada_en'],
            },
        ),
    ]
