# Generated by Django 5.2.3 on 2025-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color para mostrar en el calendario (formato hex: #RRGGBB)', max_length=7),
        ),
    ]
