# Generated by Django 5.2.3 on 2025-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_obra_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('pausada', 'Pausada'), ('completada', 'Completada')], default='pendiente', help_text='Estado actual de la obra', max_length=20),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_fin_real',
            field=models.DateField(blank=True, help_text='Fecha real de finalización de la obra', null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, help_text='Fecha real de inicio de la obra', null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='horas_trabajadas',
            field=models.IntegerField(default=0, help_text='Horas ya trabajadas en esta obra'),
        ),
    ]
