# Generated by Django 5.2.3 on 2025-06-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_obra_estado_obra_fecha_fin_real_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_fin_real',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_inicio_real',
        ),
    ]
