# Generated by Django 5.2.3 on 2025-06-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_obra_completada_remove_obra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='horas_trabajadas',
        ),
    ]
